on: [push, pull_request]
name: "SQLAlchemy >=2.0.0 versions"
jobs:
  tests:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.12"
        clickhouse-version:
          - 23.8.4.69
        sa-version: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]
    services:
      clickhouse-server:
        image: clickhouse/clickhouse-server:${{ matrix.clickhouse-version }}
        ports:
          - 8123:8123
          - 9000:9000

    name: ${{ matrix.python-version }} SA=2.0.${{ matrix.sa-version }}
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install the project
        run: uv sync --python ${{ matrix.python-version }} --locked --all-extras --dev

      - name: Install test requirements
        run: |
          # Limit each test time execution.
          uv pip install --python ${{ matrix.python-version }} pytest-timeout

      - name: Install SQLAlchemy>=2
        run: |
          # remove locked SA and then replace with the target version
          uv pip uninstall --python ${{ matrix.python-version }} sqlalchemy
          uv pip install --python ${{ matrix.python-version }} sqlalchemy==2.0.${{ matrix.sa-version }}

      - name: Run tests
        run: uv run --python ${{ matrix.python-version }} pytest --timeout=10 -v
        timeout-minutes: 2
